// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fantasy_life_i_material_API.Data;

#nullable disable

namespace fantasy_life_i_material_API.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fantasy_life_i_material_API.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gatherable")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("GatheredFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Carpentry Material",
                            Gatherable = true,
                            GatheredFrom = "[\"Starry Tree\",\"Great Starry Tree\"]",
                            LifeRequired = "Woodcuter",
                            Name = "Starry Log",
                            Type = "Log"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Smithing Material",
                            Gatherable = true,
                            GatheredFrom = "[\"Gold Deposit\",\"Great Gold Deposit\",\"Superior Gold Deposit\",\"Amazing Gold Deposit\"]",
                            LifeRequired = "Miner",
                            Name = "Swolean Gold",
                            Type = "Ore"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tailoring Material",
                            Gatherable = true,
                            GatheredFrom = "[\"Ground\"]",
                            Name = "Sunny Puff",
                            Type = "Plant"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Artistry Material",
                            Gatherable = true,
                            GatheredFrom = "[\"Ground\"]",
                            Name = "Red Anthurium",
                            Type = "Plant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
